### ISSUE TITLE
[question] [documentation] purpose of tendrl_exe_file_prefix

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#111]
What is the purpose of this `tendrl_exe_file_prefix = /tmp/.tendrl_runner`? I can't find any explanation in the documentation. It seems to be related to ansible.

**Comment by nnDarshan** [comment]
@mbukatov Tendrl uses ansible modules for some management task like service-management, package installation etc. Ansible provides an executable file for this, we place it in a location and run it and later remove it. The variable tendrl_exe_file_prefix is used to specify the location of the file.

We are trying to move the management tasks to common so that it can be used as utils(https://github.com/Tendrl/common/pull/79/commits/7a4de9d5829ecbbab0da4635de4ba018fdfccbbb) I am trying to address your concern in the PR by having a brief description about the variable in the conf file as a comment.

**Comment by r0h4n** [comment]
It has been removed now
