### ISSUE TITLE
Network interfaces in any state must be imported

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/node-agent#273]
If a network interface on the system is in the state `unknown', it doesn't get imported as part of the network inventory sync. However, the network inventory must import all the interfaces on the system, irrespective of their state, with the corresponding state also imported as part of the sync.

**Comment by GowthamShanmugam** [comment]
@brainfunked problem is when network interface is down it does not give ipv4 and netmask, so we can't calculate subnet mask. we displayed all network details in subnet details wise only. so we can't include unknown network interface details. but it is not available in global wise network details, it is available in node wise network details.please check /nodes/<node_id>/Networks/<network_id>

**Comment by GowthamShanmugam** [comment]
@brainfunked @nthomas-redhat i am not displaying networks in global wise based on state, if ip addr present i am calculating subnet and displaying networks interface based on subnet. So what happening here is if network interface goes down some time it does not have ipv4. i have checked with (ip addr) command also.
so we cant calculate subnet without ipv4 so that kind of network interfaces not displayed in  global network directory.  

But it is displayed in nodewise network directory with status.

**Comment by nthomas-redhat** [comment]
@GowthamShanmugam what if the state is 'unknown'? Are you handling that appropriately?

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat i am not doing anything with state, i am just identifying interface state and updating into etcd, if ip address  and netmask present then i am identifying subnet and updating in etcd globally. so with status i am not doing anything.

**Comment by r0h4n** [comment]
Seems like this is handled: https://github.com/Tendrl/node-agent/blame/develop/tendrl/node_agent/node_sync/network_sync.py#L161

@brainfunked please review and reopen this issue if required
