### ISSUE TITLE
node-agent is not installing gluster-integration during cluster import

### ISSUE THREAD

**Issue by fbalak** [Tendrl/node-agent#367]
I tried to import gluster trusted pool (`ImportCluster` api call) from nodes where was installed gluster and node-agent was running according to https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference. There were not installed `gluster-integration` packages. According to this comment https://github.com/Tendrl/gluster-integration/issues/133#issuecomment-288409086 and `Package Installation Reference` I assumed that I don't need `tendrl-gluster-integration` installed. When I executed `ImportCluster` api call, it failed. It worked after I installed `tendrl-gluster-integration` on nodes.
`tendrl-gluster-integration` should be installed automatically when cluster is imported or in `Package Installation Reference` documentation should be described how to install `tendrl-gluster-integration` (and `tendrl-ceph-integration`).
CC: @r0h4n

**Comment by shtripat** [comment]
@fbalak recently self and @nnDarshan tested the import cluster flow for gluster. We didnt face this issue of `tendrl-gluster-integration` not getting installed. In case of rpm based installation it works seamlessly. There is an issue in dev mode when we use pip installation of `tendrl-gluster-integration`. In this case installation fails because dependency `gstatus` doesnt have a pip installer available.

We have a WIP PR to fix this issue and ask user to install `gstatus` manually before import of cluster till we get `gstatus` pip installer available.

Let me know if you are using a dev setup or rpm based installation. Also if not able to make out, share the details of the setup in PM and I would try to debug this.

**Comment by fbalak** [comment]
@shtripat I tested it again this morning and it worked. --> closing
Tested with:
tendrl-commons-1.2.1-04_01_2017_00_59_17.noarch
tendrl-node-agent-1.2.2-04_04_2017_00_01_04.noarch
tendrl-gluster-integration-1.2.1-04_04_2017_04_38_03.noarch
