### ISSUE TITLE
Cluster synchronization

### ISSUE THREAD

**Issue by fbalak** [Tendrl/node-agent#405]
I had not yet imported cluster composed from four gluster nodes. `GetNodeList` API call returned correctly one cluster with four nodes available. Then I detached all nodes from trusted pool via bashe and tried `GetNodeList` API again. It still showed one cluster with 4 nodes. After I restarted `tendrl-node-agent` service on all nodes it started to show 4 available clusters with one node. API should return correct information about clusters without reloading `tendrl-node-agent service`.

Tested with:
tendrl-performance-monitoring-1.2.3-04_28_2017_03_02_04.noarch
tendrl-api-1.2.3-04_28_2017_01_51_05.noarch
tendrl-node-agent-1.2.3-04_28_2017_00_01_03.noarch
tendrl-node-monitoring-1.2.3-04_28_2017_04_25_04.noarch
tendrl-commons-1.2.3-04_27_2017_05_13_05.noarch

**Comment by r0h4n** [comment]
`Then I detached all nodes from trusted pool`

Tendrl doesnt de-register/unmanage nodes as such, it requires cleaning up certain keys in etcd and some package management.  This bug is invalid as of now.

@japplewhite @brainfunked  any comments on "unmanage" node in Tendrl?

**Comment by japplewhite** [comment]
@r0h4n  Unmanage cluster in the UI should make nodes show up as a simple RHEL or Centos hosts that could be added to either ceph or gluster. In other words the keys for those nodes should be cleaned up.

**Comment by r0h4n** [comment]
@brainfunked ^

**Comment by japplewhite** [comment]
@r0h4n @brainfunked @sankarshanmukhopadhyay 
I wanted to summarize our discussion on node and cluster removal.

**Node removal:**
1) We will not support node removal unless Tendrl detects that the admin has manually removed the volumes from the node in Gluster  and un-peered the node from the trusted pool.  At this point the UI will enable "Remove node". We should document this process.

For Ceph we will require that the admin has manually removed the node from the ceph Cluster.  

Node removal in these two cases will mean: We shut down the node agent, bridge processes, and collectd and set them not to start on boot. Then we remove our node metadata from Tendrl/etcd and also remove our time series data too. The node should no longer show in the UI.

_Re-enabling a node that has been removed would be handled through Ansible playbooks as if it were a new node._

**Cluster removal:**

2) In this case we shut down and disable the tendrl-* services and collectd on the cluster nodes, then remove the Tendrl/etcd information about the cluster and nodes in etcd and performance monitoring so that the disappear from the UI.

_Again adding a removed cluster would be handled via Ansible as if it's a new cluster._

**Comment by r0h4n** [comment]
Comments on from @brainfunked 

> it would be good to implement unmanage node as a separate flow. I'd like the user to have the option of selecting whether the nodes would also be unmanaged in a shrink cluster case. Same with unmanage cluster where you may want to use the same nodes later with a different cluster on an experimental setup
> Backend already has this flexibility, I see no reason to make a monolithic flow to remove the option from the user

**Comment by r0h4n** [comment]
@japplewhite I have some suggestions  

Node Removal:
I am not sure it is a good idea for Tendrl to detect patterns mentioned by you like "all volumes on a node deleted by admin manually" 

Instead

- Provide tendrl API call for "UnManage Node", which basically lets the user explicitly tell Tendrl to remove all volumes from the node in gluster and unpeers the node from Trusted pool.


Cluser removal:
tendrl-* services can be shutdown (due to failure) for various reasons,  I dont think we should assume that a shutdown tendrl-* service list indicates that user wants to remove the cluster.

Instead

- Provide a tendrl API call which allows user to mark cluster as unmanaged, the actions we take during this depends if it is a hard delete of the cluster or a soft delete. We can remove all tendrl packages from the participating nodes and clean up cluster keys in etcd during this API call.

The API driven approach to unmanage node/cluster seems much cleaner and easier to implement than detecting bunch of patterns which can be falsely detected sometimes.

Thoughts?  @japplewhite @brainfunked @sankarshanmukhopadhyay @nthomas-redhat

**Comment by shtripat** [comment]
>> Provide tendrl API call for "UnManage Node", which basically lets the user explicitly tell Tendrl to 
>> remove all volumes from the node in gluster and unpeers the node from Trusted pool.

I feel this is rather called shrink cluster

**Comment by japplewhite** [comment]
@r0h4n , @shtripat I agree this is shrink cluster and it is from a user perspective more desirable. It's what we want ideally but it places a lot of responsibility on us. We have to make sure we don't lose data or place the customer in a situation where they fall below the minimum data protection scheme for all data type. Example: EC volumes - we need to ensure we don't go below the minimum or below  replica two when shrinking a 3 way replicated vol. If you think we can do it I agree it's better but the testing would have to be quite detailed on this and the execution on the code has to be flawless, has to provide good warnings for situations where the data protection is degraded. We also need to be mindful that in production we could also impact performance and warn on that too.

**Comment by r0h4n** [comment]
@shtripat please open a Tendrl/Specification issue for shrink cluster

**Comment by shtripat** [comment]
>> please open a Tendrl/Specification issue for shrink cluster

@r0h4n, sure. will open a spec issue and attach here as well.

**Comment by shtripat** [comment]
@r0h4n raised a specification issue https://github.com/Tendrl/specifications/issues/161
