### ISSUE TITLE
Disk sync is not working in RHEL 7.4 

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#463]
In RHEL 7.4 beta release disk sync have some problem, The problem is disk sync need by-id as key in etcd for each disks, by-id is collected from hwinfo tool. But in rhel 7.4 hwinfo does not provide any by-id information for disk. Because of this problem disk sync is failing.
This is not a problem with hwinfo tool or hwinfo version, Rhel 7.4 is not giving any by-id information. hwinfo is getting by_id from /dev/disk directory, But in rhel 7.4 there is no by-id's are present. So hwinfo not able to give by_id.

**Comment by GowthamShanmugam** [comment]
Rhel 7.4 is an pre-release/testing version so is this bug is really a problem or any other suggestion?

**Comment by GowthamShanmugam** [comment]
@r0h4n @japplewhite @shtripat @nthomas-redhat @brainfunked @nnDarshan

**Comment by GowthamShanmugam** [comment]
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 Beta (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:beta:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4 Beta"
Red Hat Enterprise Linux Server release 7.4 Beta (Maipo)
Red Hat Enterprise Linux Server release 7.4 Beta (Maipo)

**Comment by GowthamShanmugam** [comment]
@dahorak in your machine, there is no by-id is present in /dev/disk/by-id, because of this problem disk sync is falling, can you please check you machine, or create one more setup and test it.

So rhel 7.4 is not problem is actually giving by-id so i am closing this issue for now.

**Comment by brainfunked** [comment]
@dahorak was there any modification to the udev rules on the machine this issue came up on?

**Comment by dahorak** [comment]
It is not RHEL 7.4 specific, it is related (probably) only to VMs.
Links in /dev/disks/by-id/* are created from disk serial number, which might not be set/available for virtual disks. (I'm not 100% sure if it might be applicable also to physical disks.)
So I think, it is not real problem for production scenario, but it might be problem for demos on virtual environment (It is possible to fix it by setting the "serial" field for the virtual disk, but it is not clear that this is the root cause of this issue)...

**Comment by shtripat** [comment]
That's correct Daniel. We were able to see this. Even on centos7.4 by-id is available.
I feel the issue here is the way virtual disks are created (as you identified already)

**Comment by dahorak** [comment]
@shtripat yep, the question is, how should Tendrl handle this situation? As it might occur on cluster created from VMs (designed for testing or as demo).

**Comment by shtripat** [comment]
@dahorak I feel missing disk by-id is not a correct scenario.
@GowthamShanmugam Is there a work around for this?

**Comment by dahorak** [comment]
@shtripat I think it is not valid _production_ scenario, but it is quite possible scenario for demo/testing cluster. So I think it would be good, if Tendrl will be able to properly handle it (at least correctly describe the issue).

**Comment by GowthamShanmugam** [comment]
@shtripat @dahorak i can see by-id in VM also,
if it is a physical machine it will give by-id in combination of serail_vendor_model, in VM it gives some uuid.

**Comment by dahorak** [comment]
In case of Libvirt/KVM, it depends on the [configuration of the disk](https://libvirt.org/formatdomain.html#elementsDisks) - if it have `<serial>...</serial>` configured, `/dev/disks/by-id/...` links are created. If `<serial>` is not present in the disk configuration section (which is perfectly valid scenario) `/dev/disks/by-id/... ` links are not created. For different virtualization tool/technology it might work slightly differently.

**Comment by shtripat** [comment]
@brainfunked in case there is no by-id field available for the disks, what should be strategy to identify the disks here?

**Comment by brainfunked** [comment]
Can we get a confirmation that by-uuid mappings are always expected to be present and persistent across reboots?

**Comment by dahorak** [comment]
AFAIK _by-uuid_ mapping is available only for partitions (but yes, it is persistent across reboots).

**Comment by brainfunked** [comment]
Well, ideally, we need at least one id scheme which can be used across all virtio disks over different VMs. Worst case, we can look to fail over to by-uuid or some such, if by-id is absent. But I would prefer not to have to jump id schemes. Also, given the new structure being discussed at https://github.com/Tendrl/commons/pull/492#issuecomment-302306277, we don't need the id scheme to be the same across multiple types of block devices. A scheme that works just for virtio devices is good enough.

Also, based on the new structure, the ids don't actually need to be persistent across reboots. Because of the way sync would work, any old id no longer present on the system would be removed from etcd. We're going to trust the system state as the source of truth and do no logic or mapping at our end, except for indexing.

@GowthamShanmugam would it be possible for you to validate whether the uuid scheme would work better for us than the id scheme?

**Comment by GowthamShanmugam** [comment]
@brainfunked we cant use by-uuid, because by-uuid is only for partitions, by-uuid is nothing but a file_system  id

**Comment by brainfunked** [comment]
@GowthamShanmugam in that case, we don't have an option but to fall back on using the block device name for the virtio device id. Of course, this would require the new structure proposed in https://github.com/Tendrl/commons/pull/492#issuecomment-302306277.

**Comment by GowthamShanmugam** [comment]
@brainfunked ok

**Comment by brainfunked** [comment]
@GowthamShanmugam btw, it would probably be a good idea to implement the fallback for any type of block device whose id is used. For now that would just be physical disks, along with the virtio devices.

**Comment by GowthamShanmugam** [comment]
@r0h4n we can close this issue
