### ISSUE TITLE
Deploy of Gluster TP fails on virtualbox eth1 cluster network

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/node-agent#498]
On VirtualBox I need to select an alternate network from the one the installer detects as the cluster network (eth0 / 10.0.2.0/24) . I do so by selecting the drop down and selecting the second network. When doing so the installation wizard then incorrectly reports "warning Mandatory parameter Cluster.public_network not provided"  followed by "warning Mandatory parameter Cluster.conf_overrides not provided "
and fails with "error Job failed list.remove(x): x not in list: list.remove(x): x not in list"

@r0h4n

**Comment by r0h4n** [comment]
@nnDarshan Whats your take on this?

**Comment by nnDarshan** [comment]
@r0h4n The warning messages mentioned above are expected.
 The error mentioned "error Job failed list.remove(x): x not in list: list.remove(x): x not in list" this occurred because the node list(value of  "Node[]") sent in the job doesn't contain the node_id(obtained from NS.node_context.node_id) of the current node.
Not sure if API/UI is creating this difference.
@anivargi @cloudbehl Any thoughts ?

**Comment by r0h4n** [comment]
@GowthamShanmugam Has tested virtualbox with tendrl, he didnt find any of such errors, @japplewhite can you try to reproduce this issue
